update surahs set arabicname= N'الْفَاتِحَة' where surahNumber=1
update surahs set arabicname= N'الْبَقَرَة' where surahNumber=2
update surahs set arabicname= N'آل عِمْرَان' where surahNumber=3
update surahs set arabicname= N'النِّسَآء' where surahNumber=4
update surahs set arabicname= N'الْمَآئِدَة' where surahNumber=5
update surahs set arabicname= N'الْأَنْعَام' where surahNumber=6
update surahs set arabicname= N'الْأَعْرَاف' where surahNumber=7
update surahs set arabicname= N'الْأَنْفَال' where surahNumber=8
update surahs set arabicname= N'التَّوْبَة' where surahNumber=9
update surahs set arabicname= N'يُوْنـُس' where surahNumber=10
update surahs set arabicname= N'هُوْد' where surahNumber=11
update surahs set arabicname= N'يُوْسُف' where surahNumber=12
update surahs set arabicname= N'الرَّعْد' where surahNumber=13
update surahs set arabicname= N'إِبْرَاهِيْم' where surahNumber=14
update surahs set arabicname= N'الْحِجْر' where surahNumber=15
update surahs set arabicname= N'النَّحْل' where surahNumber=16
update surahs set arabicname= N'الْإِسْرَاء - - بَنِيْ إِسْرَآءِيْل' where surahNumber=17
update surahs set arabicname= N'الْكَهْف' where surahNumber=18
update surahs set arabicname= N'مَرْيَم' where surahNumber=19
update surahs set arabicname= N'طهٰ' where surahNumber=20
update surahs set arabicname= N'الْأَنْبِيَآء' where surahNumber=21
update surahs set arabicname= N'الْحَجّ' where surahNumber=22
update surahs set arabicname= N'الْمُؤْمِنُوْن' where surahNumber=23
update surahs set arabicname= N'النُّوْر' where surahNumber=24
update surahs set arabicname= N'الْفُرْقَان' where surahNumber=25
update surahs set arabicname= N'الشُّعَرَآء' where surahNumber=26
update surahs set arabicname= N'النَّمْل' where surahNumber=27
update surahs set arabicname= N'الْقَصَص' where surahNumber=28
update surahs set arabicname= N'الْعَنْکَبُوْت' where surahNumber=29
update surahs set arabicname= N'الرُّوْم' where surahNumber=30
update surahs set arabicname= N'لُقْمَان' where surahNumber=31
update surahs set arabicname= N'السَّجْدَة' where surahNumber=32
update surahs set arabicname= N'الْأَحْزَاب' where surahNumber=33
update surahs set arabicname= N'سَبـَا' where surahNumber=34
update surahs set arabicname= N'فَاطِر' where surahNumber=35
update surahs set arabicname= N'يٰس' where surahNumber=36
update surahs set arabicname= N'الصَّافَّات' where surahNumber=37
update surahs set arabicname= N'ص' where surahNumber=38
update surahs set arabicname= N'الزُّمَر' where surahNumber=39
update surahs set arabicname= N'غَافِر - الْمُؤْمِن' where surahNumber=40
update surahs set arabicname= N'فُصِّلَت - حٰم السَّجْدَة' where surahNumber=41
update surahs set arabicname= N'الشُّوْرٰی' where surahNumber=42
update surahs set arabicname= N'الزُّخْرُف' where surahNumber=43
update surahs set arabicname= N'الدُّخَان' where surahNumber=44
update surahs set arabicname= N'الْجَاثِيَة' where surahNumber=45
update surahs set arabicname= N'الْأَحْقَاف' where surahNumber=46
update surahs set arabicname= N'مُحَمَّد' where surahNumber=47
update surahs set arabicname= N'الْفَتْح' where surahNumber=48
update surahs set arabicname= N'الْحُجُرَات' where surahNumber=49
update surahs set arabicname= N'ق' where surahNumber=50
update surahs set arabicname= N'الذَّارِيَات' where surahNumber=51
update surahs set arabicname= N'الطُّوْر' where surahNumber=52
update surahs set arabicname= N'النَّجْم' where surahNumber=53
update surahs set arabicname= N'الْقَمَر' where surahNumber=54
update surahs set arabicname= N'الرَّحْمٰن' where surahNumber=55
update surahs set arabicname= N'الْوَاقِعَة' where surahNumber=56
update surahs set arabicname= N'الْحَدِيْد' where surahNumber=57
update surahs set arabicname= N'الْمُجَادَلَة' where surahNumber=58
update surahs set arabicname= N'الْحَشْر' where surahNumber=59
update surahs set arabicname= N'الْمُمْتَحِنَة' where surahNumber=60
update surahs set arabicname= N'الصَّفّ' where surahNumber=61
update surahs set arabicname= N'الْجُمُعَة' where surahNumber=62
update surahs set arabicname= N'الْمُنَافِقُوْن' where surahNumber=63
update surahs set arabicname= N'التَّغَابُن' where surahNumber=64
update surahs set arabicname= N'الطَّلاَق' where surahNumber=65
update surahs set arabicname= N'التَّحْرِيْم' where surahNumber=66
update surahs set arabicname= N'الْمُلْک' where surahNumber=67
update surahs set arabicname= N'الْقَلَم' where surahNumber=68
update surahs set arabicname= N'الْحَآقَّة' where surahNumber=69
update surahs set arabicname= N'الْمَعَارِج' where surahNumber=70
update surahs set arabicname= N'نُوْح' where surahNumber=71
update surahs set arabicname= N'الْجِنّ' where surahNumber=72
update surahs set arabicname= N'الْمُزَّمِّل' where surahNumber=73
update surahs set arabicname= N'الْمُدَّثِّر' where surahNumber=74
update surahs set arabicname= N'الْقِيَامَة' where surahNumber=75
update surahs set arabicname= N'الْإِنْسَان - الدَّهْر' where surahNumber=76
update surahs set arabicname= N'الْمُرْسَلاَت' where surahNumber=77
update surahs set arabicname= N'النَّبَا' where surahNumber=78
update surahs set arabicname= N'النَّازِعَات' where surahNumber=79
update surahs set arabicname= N'عَبَسَ' where surahNumber=80
update surahs set arabicname= N'التَّکْوِيْر' where surahNumber=81
update surahs set arabicname= N'الْإِنْفِطَار' where surahNumber=82
update surahs set arabicname= N'الْمُطَفِّفِيْن' where surahNumber=83
update surahs set arabicname= N'الْإِنْشِقَاق' where surahNumber=84
update surahs set arabicname= N'الْبُرُوْج' where surahNumber=85
update surahs set arabicname= N'الطَّارِق' where surahNumber=86
update surahs set arabicname= N'الْأَعْلیٰ' where surahNumber=87
update surahs set arabicname= N'الْغَاشِيَة' where surahNumber=88
update surahs set arabicname= N'الْفَجْر' where surahNumber=89
update surahs set arabicname= N'الْبَلَد' where surahNumber=90
update surahs set arabicname= N'الشَّمْس' where surahNumber=91
update surahs set arabicname= N'اللَّيْل' where surahNumber=92
update surahs set arabicname= N'الضُّحٰی' where surahNumber=93
update surahs set arabicname= N'الشَّرْح - - الْإِنْشِرَاح' where surahNumber=94
update surahs set arabicname= N'التِّيْن' where surahNumber=95
update surahs set arabicname= N'الْعَلَق' where surahNumber=96
update surahs set arabicname= N'الْقَدْر' where surahNumber=97
update surahs set arabicname= N'الْبَـيِّـنَة' where surahNumber=98
update surahs set arabicname= N'الزَّلْزَلَة - - الزِّلْزَال' where surahNumber=99
update surahs set arabicname= N'الْعَادِيَات' where surahNumber=100
update surahs set arabicname= N'الْقَارِعَة' where surahNumber=101
update surahs set arabicname= N'التَّکَاثُر' where surahNumber=102
update surahs set arabicname= N'الْعَصْر' where surahNumber=103
update surahs set arabicname= N'الْهُمَزَة' where surahNumber=104
update surahs set arabicname= N'الْفِيل' where surahNumber=105
update surahs set arabicname= N'قُرَيْش' where surahNumber=106
update surahs set arabicname= N'الْمَاعُوْن' where surahNumber=107
update surahs set arabicname= N'الْکَوْثَر' where surahNumber=108
update surahs set arabicname= N'الْکَافِرُوْن' where surahNumber=109
update surahs set arabicname= N'النَّصْر' where surahNumber=110
update surahs set arabicname= N'الْمَسَد - - اللَّهَب' where surahNumber=111
update surahs set arabicname= N'الْإِخْلاَص' where surahNumber=112
update surahs set arabicname= N'الْفَلَق' where surahNumber=113
update surahs set arabicname= N'النَّاس' where surahNumber=114